meta.db.url=jdbc:postgresql://localhost:5433/public
meta.db.user=postgres
meta.db.pass=0000
meta.db.schema=public

worker.db.urls=jdbc:postgresql://localhost:5433/w1,jdbc:postgresql://localhost:5434/w2
worker.db.user=postgres
worker.db.pass=password
